### ISSUE TITLE
Error: Server is not accessible [temporary only]

### ISSUE THREAD

**Issue by MartindForlon** [Marginal/EDMarketConnector#149]
After installing latest version I cannot connect to the server for some reason. Tried more times actualise without success. Interesting is that data sent to EDSM are working, I logged into my account there and it had my last position saved.

In log file is next:
Traceback (most recent call last):
  File "EDMarketConnector.py", line 14, in <module>
  File "Tkinter.pyo", line 38, in <module>
  File "FixTk.pyo", line 65, in <module>
  File "_tkinter.pyo", line 12, in <module>
  File "_tkinter.pyo", line 10, in __load
ImportError: DLL load failed: Proces nemá přístup k souboru, neboť jej právě využívá jiný proces.
Traceback (most recent call last):
  File "EDMarketConnector.py", line 14, in <module>
  File "Tkinter.pyo", line 38, in <module>
  File "FixTk.pyo", line 65, in <module>
  File "_tkinter.pyo", line 12, in <module>
  File "_tkinter.pyo", line 10, in __load
ImportError: DLL load failed: Proces nemá přístup k souboru, neboť jej právě využívá jiný proces.

**Comment by MartindForlon** [comment]
hmm, temporary issue it seems, actualisations going now normally. Sorry for false alarm.

**Comment by Marginal** [comment]
This is an odd error. Perhaps the installer had not finished?
Closing this, but please re-open if it happens again.
