### ISSUE TITLE
Last version won't launch

### ISSUE THREAD

**Issue by jlestrohan** [Marginal/EDMarketConnector#230]
Sorry if I have missed anything , here's ED log:

E:D Market Connector 2.3.6.0 2017-08-15T22:30:29
loading plugin collate
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin commodity
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin companion
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin config
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin coriolis
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin eddb
loading plugin eddn
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin EDMC
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 39, in __init__
  File "C:\Program Files (x86)\EDMarketConnector\EDMC.py", line 34, in <module>
AttributeError: 'module' object has no attribute 'EDDB'
loading plugin edshipyard
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin edsm
loading plugin hotkey
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin interactions
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin l10n
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin loadout
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin monitor
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin myNotebook
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin outfitting
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
loading plugin plug
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
  File "plug.pyo", line 40, in __init__
AttributeError: 'module' object has no attribute 'plugin_start'
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
AttributeError: Config instance has no attribute 'internal_plugin_dir'
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
AttributeError: Config instance has no attribute 'internal_plugin_dir'
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
AttributeError: Config instance has no attribute 'internal_plugin_dir'
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
AttributeError: Config instance has no attribute 'internal_plugin_dir'
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
AttributeError: Config instance has no attribute 'internal_plugin_dir'
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
AttributeError: Config instance has no attribute 'internal_plugin_dir'
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
AttributeError: Config instance has no attribute 'internal_plugin_dir'
Traceback (most recent call last):
  File "plug.pyo", line 109, in load_plugins
AttributeError: Config instance has no attribute 'internal_plugin_dir'
Traceback (most recent call last):
  File "EDMarketConnector.py", line 894, in <module>
    self.status['text'] = unicode(e)
  File "EDMarketConnector.py", line 95, in __init__
    plug.load_plugins()
  File "plug.pyo", line 114, in load_plugins
AttributeError: 'dict' object has no attribute 'extend'
---------------------------------------------------------------------------------------

Help welcome :)

**Comment by inorton** [comment]
Hiya, that does look a little odd! It looks like you have the EDMC source code inside your plugins folder

**Comment by inorton** [comment]
Are you running the installer version?

**Comment by jlestrohan** [comment]
Hey Ian

Thank you for your quick reply
Yes I have reinstalled it several times from the.msi provided on the github project file (Windows) taking great care of cleaning the left over files between two installations... no luck so far. The previous version worked fine as I also attempted to reinstall it after the previous failures to check it..

I stay at your entire disposal should you need more information :)

**Comment by Marginal** [comment]
Please:
- Uninstall from the Control Panel
- Delete the folder `C:\Program Files (x86)\EDMarketConnector`
- Reinstall the [latest .msi](https://github.com/Marginal/EDMarketConnector/releases/latest)
