### ISSUE TITLE
Error when trying to run EDMarketConnector.py

### ISSUE THREAD

**Issue by Grotster** [Marginal/EDMarketConnector#284]
I am getting the following output when trying to run EDMarketConnector.py

`C:\Python27\Scripts>python.exe C:\Users\*masked*\Downloads\EDMarketConnector-rel-248\EDMarketConnector-rel-248\EDMarketConnector.py
Traceback (most recent call last):
  File "C:\Users\*masked*\Downloads\EDMarketConnector-rel-248\EDMarketConnector-rel-248\EDMarketConnector.py", line 19, in <module>
    from config import appname, applongname, appversion, config
  File "C:\Users\*masked*\Downloads\EDMarketConnector-rel-248\EDMarketConnector-rel-248\config.py", line 377, in <module>
    config = Config()
  File "C:\Users\*masked*\Downloads\EDMarketConnector-rel-248\EDMarketConnector-rel-248\config.py", line 223, in __init__
    self.set('outdir', KnownFolderPath(FOLDERID_Documents))
  File "C:\Users\*masked*\Downloads\EDMarketConnector-rel-248\EDMarketConnector-rel-248\config.py", line 258, in set
    raise NotImplementedError()
NotImplementedError

C:\Python27\Scripts>`

I am trying to run from source because my AV appears to be blocking installation from the msi and I am unable to disable it.

**Comment by Grotster** [comment]
I managed to get the msi to install but I am seeing this in the EDMarketConnector.exe.log file

`Traceback (most recent call last):
  File "EDMarketConnector.py", line 19, in <module>
  File "config.pyo", line 383, in <module>
  File "config.pyo", line 227, in __init__
  File "config.pyo", line 262, in set
NotImplementedError`

**Comment by Marginal** [comment]
Please copy and paste the following into a console window (replacing "you" with your username):
```cmd
cd C:\Users\you\Downloads\EDMarketConnector-rel-248\EDMarketConnector-rel-248
C:\Python27\python.exe -c "import config; print config.KnownFolderPath(config.FOLDERID_Documents)"
```
and let me know what it says.

**Comment by Grotster** [comment]
Here is the output...

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "config.py", line 377, in <module>
    config = Config()
  File "config.py", line 223, in __init__
    self.set('outdir', KnownFolderPath(FOLDERID_Documents))
  File "config.py", line 258, in set
    raise NotImplementedError()
NotImplementedError`

**Comment by Grotster** [comment]
I see where you are coming from... My profile path is set to a remote drive that is currently not connected. I connected the remote drive and the application launches.

**Comment by Grotster** [comment]
Thanks Jonathon, I got it to work and closed the issue with some notes.


-- Sent from my iPhone --

On Jan 12, 2018, at 01:02, Jonathan Harris <notifications@github.com<mailto:notifications@github.com>> wrote:


Please copy and paste the following into a console window (replacing "you" with your username):

cd C:\Users\you\Downloads\EDMarketConnector-rel-248\EDMarketConnector-rel-248
C:\Python27\python.exe -c "import config; print config.KnownFolderPath(config.FOLDERID_Documents)"

and let me know what it says.
