### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by Gousaid67** [Marginal/EDMarketConnector#355]
Hello, Every time i attempt to launch the app, it always crashes with this error in the logs

Traceback (most recent call last):
  File "EDMarketConnector.py", line 44, in <module>
  File "l10n.pyo", line 18, in <module>
  File "locale.pyo", line 581, in setlocale
locale.Error: unsupported locale setting
Traceback (most recent call last):
  File "EDMarketConnector.py", line 44, in <module>
  File "l10n.pyo", line 18, in <module>
  File "locale.pyo", line 581, in setlocale
locale.Error: unsupported locale setting
Traceback (most recent call last):
  File "EDMarketConnector.py", line 44, in <module>
  File "l10n.pyo", line 18, in <module>
  File "locale.pyo", line 581, in setlocale
locale.Error: unsupported locale setting

seems like i may be missing a locale setting but it might be something else.

**Comment by Marginal** [comment]
That's odd.
What OS are you using, what language, and what are your region and language settings?

**Comment by Gousaid67** [comment]
Im using Windows 10 Home (the newer builds), my system language is English(US), my region is Sweden and English(US) Encompasses all of the setting(Default App and Windows Display Language.

**Comment by Marginal** [comment]
Can't reproduce this problem, but next release will have a workaround .
