### ISSUE TITLE
Cannot run in ArchLinux from source, or Wine

### ISSUE THREAD

**Issue by lehthanis** [Marginal/EDMarketConnector#418]
This may not be the best place to bring this up, and if you'd rather I contact you directly or post elsewhere, I understand...I tried gettign this to run from source on ArchLinux, but even though I have python keyring installed, whenever I try to run EDMarketConnector.py I get:
```
» [~/.bin/EDMarketConnector] ./EDMarketConnector.py 
Traceback (most recent call last):
  File "./EDMarketConnector.py", line 9, in <module>
    import keyring
ImportError: No module named keyring
```
So I instead figured it should at least run under Wine...when I installed it, I run it and it says check the log...the log reports:
```
Traceback (most recent call last):
  File "EDMarketConnector.py", line 48, in <module>
  File "stats.pyo", line 17, in <module>
  File "prefs.pyo", line 59, in <module>
  File "ctypes\__init__.pyo", line 379, in __getattr__
  File "ctypes\__init__.pyo", line 384, in __getitem__
AttributeError: function 'CalculatePopupWindowPosition' not found
Traceback (most recent call last):
  File "EDMarketConnector.py", line 48, in <module>
  File "stats.pyo", line 17, in <module>
  File "prefs.pyo", line 59, in <module>
  File "ctypes\__init__.pyo", line 379, in __getattr__
  File "ctypes\__init__.pyo", line 384, in __getitem__
AttributeError: function 'CalculatePopupWindowPosition' not found
```

Any ideas on which way I should go to get this to work?  Now that ED runs beautifully under Proton 4.2, this is probably going to come up a lot.

**Comment by Marginal** [comment]
Don't actually need "keyring" any more since Frontier implemented proper cAPI authentication, so 2a557fd drops the requirement.

I haven't really done any testing on Arch Linux. You'll probably need `app add python2-tkinter`. "iniparse" and "requests" you can install with `pip`.
