### ISSUE TITLE
Where is the shipyard module?

### ISSUE THREAD

**Issue by stephen304** [Marginal/EDMarketConnector#42]
I'm trying to run it from the source on arch. I've installed the required packages and edited ./EDMarketConnector.py to use "python2" instead of "python" (python3), but when I run it, I get this:

    Traceback (most recent call last):
      File "./EDMarketConnector.py", line 21, in <module>
        import companion
      File "/home/stephen/git/EDMarketConnector-rel-187/companion.py", line 14, in <module>
        from shipyard import ship_map
    ImportError: No module named shipyard

Searching the whole folder I don't see any shipyard module. Any ideas?

**Comment by Marginal** [comment]
Oops. Sorry about that.
