### ISSUE TITLE
Doesn't work with Ubuntu 20.04 because of the python3 change

### ISSUE THREAD

**Issue by alex-williams** [Marginal/EDMarketConnector#501]
Attempting to run './EDMarketConnector.py' on the command line fails with 

```
Traceback (most recent call last):
  File "./EDMarketConnector.py", line 12, in <module>
    import requests
ImportError: No module named requests
```

Commenting out the 'import requests' line and running again, leads to the following

```
Traceback (most recent call last):
  File "./EDMarketConnector.py", line 18, in <module>
    from config import appname, applongname, appversion, config
  File "/home/alex-williams/Brighter/Git-Repositories/EDMarketConnector/config.py", line 89, in <module>
    from iniparse import RawConfigParser
ImportError: No module named iniparse
```

Unfortunately, Ubuntu have screwed around with Python2, because it's end of life and have dropped python2-requests as a package entirely, trying to install the deb package for python-requests_2 from 19.10, results in a missing dependency that cannot be installed, etc. I'm imagining this is going to be a recurring theme... they've bodged python2 in to offer some backward compatibility, but the operative word is *some*.

I noticed a Python3 branch, but it's stale, any chance of some movement? I'll take a look and see if I can make it work in python3 if I have time.

**Comment by alex-williams** [comment]
So, not actually an issue, as the python3 branch works. I made an assumption it didn't because it was showing as stale. I've added to the Linux installation instructions, to avoid people like me jumping to this conclusion again and created a pull request for it, linked below if you want to include it. I'll close this issue now.

https://github.com/Marginal/EDMarketConnector/pull/502
